-- MySQL Script generated by MySQL Workbench
-- 11/05/16 21:50:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tramap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tramap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tramap` DEFAULT CHARACTER SET utf8 ;
USE `tramap` ;

-- -----------------------------------------------------
-- Table `tramap`.`sport_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramap`.`sport_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramap`.`user_identity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramap`.`user_identity` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NULL,
  `email` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramap`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramap`.`location` (
  `id` INT NOT NULL,
  `position` VARCHAR(45) NULL,
  `event_track` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tramap`.`event_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramap`.`event_time` (
  `id` INT NOT NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tramap`.`event_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramap`.`event_status` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tramap`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramap`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sport_category_id` INT NOT NULL,
  `owner_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `event_time_id` INT NOT NULL,
  `event_status_id` INT NOT NULL,
  PRIMARY KEY (`id`, `event_status_id`),
  INDEX `fk_events_Category_idx` (`sport_category_id` ASC),
  INDEX `fk_events_user_identity1_idx` (`owner_id` ASC),
  INDEX `fk_event_location1_idx` (`location_id` ASC),
  INDEX `fk_event_event_time1_idx` (`event_time_id` ASC),
  INDEX `fk_event_event_status1_idx` (`event_status_id` ASC),
  CONSTRAINT `fk_events_Category`
    FOREIGN KEY (`sport_category_id`)
    REFERENCES `tramap`.`sport_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_user_identity1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `tramap`.`user_identity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `tramap`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_event_time1`
    FOREIGN KEY (`event_time_id`)
    REFERENCES `tramap`.`event_time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_event_status1`
    FOREIGN KEY (`event_status_id`)
    REFERENCES `tramap`.`event_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramap`.`user_login_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramap`.`user_login_status` (
  `id` CHAR(10) NULL,
  `description` VARCHAR(64) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tramap`.`user_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramap`.`user_login` (
  `user_id` INT NOT NULL,
  `login` VARCHAR(64) NULL,
  `password` VARCHAR(64) NULL,
  `status` CHAR(10) NULL,
  `failed_attempts` INT NULL,
  INDEX `fk_user_login_user_identity1_idx` (`user_id` ASC),
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_login_user_login_status1_idx` (`status` ASC),
  CONSTRAINT `fk_user_login_user_identity1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tramap`.`user_identity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_login_user_login_status1`
    FOREIGN KEY (`status`)
    REFERENCES `tramap`.`user_login_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tramap`.`user_reset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramap`.`user_reset` (
  `user_id` INT NOT NULL,
  `token` VARCHAR(64) NULL,
  `expire_time` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_reset_user_identity1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tramap`.`user_identity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tramap`.`event_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tramap`.`event_meta` (
  `event_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(256) NULL,
  PRIMARY KEY (`event_id`),
  INDEX `fk_Event_meta_events1_idx` (`event_id` ASC),
  CONSTRAINT `fk_Event_meta_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `tramap`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
